# Generated by Django 4.2.6 on 2023-10-09 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_posts_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='likes',
            field=models.ManyToManyField(null=True, to='app.udata'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='topics',
            field=models.ManyToManyField(null=True, to='app.topic'),
        ),
    ]
