# Generated by Django 4.2.6 on 2023-10-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_posts_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, to='app.topic'),
        ),
    ]
