# Generated by Django 4.2.1 on 2023-10-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_posts_topics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="likes",
            field=models.ManyToManyField(blank=True, to="app.udata"),
        ),
        migrations.AlterField(
            model_name="posts",
            name="topics",
            field=models.ManyToManyField(blank=True, to="app.topic"),
        ),
    ]
