# Generated by Django 4.2.1 on 2023-10-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_posts_likes_alter_posts_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="udata",
            name="avatar",
            field=models.ImageField(default="avatar.svg", null=True, upload_to=""),
        ),
    ]
